### ISSUE TITLE
Updated episode source code

### ISSUE THREAD

**Issue by ghost** [ryanb/railscasts-episodes#9]
I've benefited from railscasts more than any information on rails out there, (even stackoverflow is distant 2nd), but getting the usefulness of a railscast ported into the latest version of rails is the biggest (perhaps still minor) challenge to a noob.  

Since the episodes are open-source on github, can anyone update the episodes?  Where would they be visible?

**Comment by ryanb** [comment]
The source code is all in this repository, so feel free to fork it and change to your liking. I probably won't pull any changes in because I want this to be a representation of what is covered in the screencast, however I will link to other forks if they prove valuable. Does that answer your question?

**Comment by ghost** [comment]
Yep, that's it.  Any linking to this updated work would be a goldmine to the learner.  Where would the links to the updated forks be?  Has there been much of this?

**Comment by ryanb** [comment]
@thejonster I would put it in the root README file. I haven't heard of many forks which have done this so there aren't any listed.
